import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import '@/app/ui.css'
import Particles from "@/components/magicui/particles";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
         <div className="fixed h-screen w-screen  ">
        <Particles
          className=" fixed h-screen w-screen opacity-80 z-0"
          size={1}
          quantity={500}
        />
      </div>
        {children}
       <Footer />
      </body>
    </html>
  );
}
